/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaopagamentos.view;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author breno
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeUsuarioLogado = new javax.swing.JLabel();
        txtCargoUsuarioLogado = new javax.swing.JLabel();
        labelPagamentos = new javax.swing.JLabel();
        txtPagamentosRegistrados = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionarios = new javax.swing.JMenu();
        menuRegistrarFunc = new javax.swing.JMenuItem();
        menuConsultarFunc = new javax.swing.JMenuItem();
        menuImportarFuncionarios = new javax.swing.JMenuItem();
        menuPagamentos = new javax.swing.JMenu();
        menuRegistrarPag = new javax.swing.JMenuItem();
        menuConsultarPag = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuExportarDados = new javax.swing.JMenuItem();
        menuImportarDados = new javax.swing.JMenuItem();
        menuConfigSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPagamentos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPagamentos.setText("Pagamentos Registrados:");

        txtPagamentosRegistrados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        menuFuncionarios.setText("Funcionarios");

        menuRegistrarFunc.setText("Novo");
        menuFuncionarios.add(menuRegistrarFunc);

        menuConsultarFunc.setText("Consultar");
        menuFuncionarios.add(menuConsultarFunc);

        menuImportarFuncionarios.setText("Importar");
        menuFuncionarios.add(menuImportarFuncionarios);

        jMenuBar1.add(menuFuncionarios);

        menuPagamentos.setText("Pagamentos");

        menuRegistrarPag.setText("Novo");
        menuPagamentos.add(menuRegistrarPag);

        menuConsultarPag.setText("Consultar");
        menuConsultarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarPagActionPerformed(evt);
            }
        });
        menuPagamentos.add(menuConsultarPag);

        jMenuBar1.add(menuPagamentos);

        menuConfig.setText("Configurações");

        menuExportarDados.setText("Exportar Dados");
        menuConfig.add(menuExportarDados);

        menuImportarDados.setText("Importar Dados");
        menuConfig.add(menuImportarDados);

        menuConfigSistema.setText("Sistema");
        menuConfig.add(menuConfigSistema);

        jMenuBar1.add(menuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCargoUsuarioLogado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeUsuarioLogado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPagamentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPagamentosRegistrados)))
                        .addGap(0, 595, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCargoUsuarioLogado))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPagamentos)
                            .addComponent(txtPagamentosRegistrados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                        .addComponent(txtNomeUsuarioLogado)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsultarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultarPagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelPagamentos;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuConfigSistema;
    private javax.swing.JMenuItem menuConsultarFunc;
    private javax.swing.JMenuItem menuConsultarPag;
    private javax.swing.JMenuItem menuExportarDados;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenuItem menuImportarDados;
    private javax.swing.JMenuItem menuImportarFuncionarios;
    private javax.swing.JMenu menuPagamentos;
    private javax.swing.JMenuItem menuRegistrarFunc;
    private javax.swing.JMenuItem menuRegistrarPag;
    private javax.swing.JLabel txtCargoUsuarioLogado;
    private javax.swing.JLabel txtNomeUsuarioLogado;
    private javax.swing.JLabel txtPagamentosRegistrados;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuConfigSistema() {
        return menuConfigSistema;
    }

    public JMenuItem getMenuConsultarFunc() {
        return menuConsultarFunc;
    }

    public JMenuItem getMenuConsultarPag() {
        return menuConsultarPag;
    }

    public JMenuItem getMenuRegistrarFunc() {
        return menuRegistrarFunc;
    }

    public JMenuItem getMenuRegistrarPag() {
        return menuRegistrarPag;
    }    

    public JMenuItem getMenuExportarDados() {
        return menuExportarDados;
    }

    public JMenuItem getMenuImportarDados() {
        return menuImportarDados;
    }

    public JLabel getTxtCargoUsuarioLogado() {
        return txtCargoUsuarioLogado;
    }

    public JLabel getTxtNomeUsuarioLogado() {
        return txtNomeUsuarioLogado;
    }

    public JLabel getTxtPagamentosRegistrados() {
        return txtPagamentosRegistrados;
    }

    public JMenuItem getMenuImportarFuncionarios() {
        return menuImportarFuncionarios;
    }
    
    
}
