/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaopagamentos.view;

import javax.swing.JMenuItem;

/**
 *
 * @author breno
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuarioLogado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionarios = new javax.swing.JMenu();
        menuConsultarFunc = new javax.swing.JMenuItem();
        menuRegistrarFunc = new javax.swing.JMenuItem();
        menuPagamentos = new javax.swing.JMenu();
        menuConsultarPag = new javax.swing.JMenuItem();
        menuRegistrarPag = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuConfigSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFuncionarios.setText("Funcionarios");

        menuConsultarFunc.setText("Consultar");
        menuFuncionarios.add(menuConsultarFunc);

        menuRegistrarFunc.setText("Registrar");
        menuFuncionarios.add(menuRegistrarFunc);

        jMenuBar1.add(menuFuncionarios);

        menuPagamentos.setText("Pagamentos");

        menuConsultarPag.setText("Consultar");
        menuConsultarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarPagActionPerformed(evt);
            }
        });
        menuPagamentos.add(menuConsultarPag);

        menuRegistrarPag.setText("Registrar");
        menuPagamentos.add(menuRegistrarPag);

        jMenuBar1.add(menuPagamentos);

        menuConfig.setText("Configurações");

        menuConfigSistema.setText("Sistema");
        menuConfig.add(menuConfigSistema);

        jMenuBar1.add(menuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(788, Short.MAX_VALUE)
                .addComponent(txtUsuarioLogado)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuarioLogado)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsultarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultarPagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuConfigSistema;
    private javax.swing.JMenuItem menuConsultarFunc;
    private javax.swing.JMenuItem menuConsultarPag;
    private javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenu menuPagamentos;
    private javax.swing.JMenuItem menuRegistrarFunc;
    private javax.swing.JMenuItem menuRegistrarPag;
    private javax.swing.JLabel txtUsuarioLogado;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuConfigSistema() {
        return menuConfigSistema;
    }

    public JMenuItem getMenuConsultarFunc() {
        return menuConsultarFunc;
    }

    public JMenuItem getMenuConsultarPag() {
        return menuConsultarPag;
    }

    public JMenuItem getMenuRegistrarFunc() {
        return menuRegistrarFunc;
    }

    public JMenuItem getMenuRegistrarPag() {
        return menuRegistrarPag;
    }    
}
